import { Department, Gender, User } from "@/generated/prisma";

export type ViewMode = "LIST" | "TILE" | "THUMBNAIL";

export const res: { users: User[] } = {
  users: [
    {
      email: "alice@example.com",
      name: "Alice",
      address: "123 Main Street",
      cohort: "013",
      department: Department.CM,
      dob: new Date("2000-05-15"),
      facebook: "https://facebook.com/johndoe",
      gender: Gender.MALE,
      major: "Computer Science",
      phone: "09123456789",
      school_email: "john.doe@sinhvien.edu.vn",
      roll_number: "SV001",
    },
    {
      email: "bob@example.com",
      name: "Bob",
      address: "456 Oak Avenue",
      cohort: "014",
      department: Department.TT,
      dob: new Date("2001-08-20"),
      facebook: "https://facebook.com/janesmith",
      gender: Gender.FEMALE,
      major: "Information Systems",
      phone: "09876543210",
      school_email: "jane.smith@sinhvien.edu.vn",
      roll_number: "SV002",
    },
    {
      email: "cily@example.com",
      name: "Cily",
      address: "789 Pine Road",
      cohort: "015",
      department: Department.DN,
      dob: new Date("1999-12-01"),
      facebook: "https://facebook.com/alexnguyen",
      gender: Gender.OTHER,
      major: "Software Engineering",
      phone: "09012345678",
      school_email: "alex.nguyen@sinhvien.edu.vn",
      roll_number: "SV003",
    },
    {
      email: "dany@example.com",
      name: "Dany",
      address: "789 Pine Road",
      cohort: "015",
      department: Department.VH,
      dob: new Date("2003-2-21"),
      facebook: "https://facebook.com/alexnguyen",
      gender: Gender.OTHER,
      major: "Software Engineering",
      phone: "09012345678",
      school_email: "alex.nguyen@sinhvien.edu.vn",
      roll_number: "SV004",
    },
    {
      email: "eika@example.com",
      name: "Eika",
      address: "789 Pine Road",
      cohort: "015",
      department: Department.ND,
      dob: new Date("2002-1-11"),
      facebook: "https://facebook.com/alexnguyen",
      gender: Gender.OTHER,
      major: "Software Engineering",
      phone: "09012345678",
      school_email: "alex.nguyen@sinhvien.edu.vn",
      roll_number: "SV005",
    },
  ],
};
